# Python Lesson 3 Practice Assignment

1. Create a dictionary where the keys are the names of months and the values are the number of days in that month. Allow a user to enter the name of a month and print the number of days in that month. Create appropriate prompts and print statements so the user knows what to do and can interpret the response.

In [11]:
month_dict = {
    'January': 31,
    'February': 28,
    'March': 31,
    'April': 30,
    'May': 31,
    'June': 30,
    'July': 31,
    'August': 31,
    'September': 30,
    'October': 31,
    'November': 30,
    'December': 31
}
User_input = input("Enter a month: ")
if User_input in month_dict:
    print("There are" , month_dict[User_input] , "days in" , User_input)


There are 31 days in May


2. Using the statement that creates the dictionary that is a catolog of items (below), create another dictionary with exactly the same items and keys, but for which the values are prices as decimal numbers. Let the user type in a catalog number, then print the name of the item and its price. Prepend a dollar sign `$` to the price before printing, but don’t include the dollar sign in the dictionary.

In [14]:
catalog = {'1008':'widget', '2149':'flange', '19x5':'smoke shifter', '992':'poiuyt'}
price_dict = {}
for catalog_number, item_name in catalog.items():
    price = float(input(f"Enter the price for {item_name}: "))
    price_dict[catalog_number] = price

user_input = input("Enter a catalog number: ")
if user_input in price_dict:
    item_name = catalog[user_input]
    price = price_dict[user_input]
    print(f"The item {item_name} has a price of ${price:.2f}")


The item smoke shifter has a price of $450.00


3. Modify the last program to convert the price of the selected item to euros (you may need to look up the exchange rate). Add an additional statement to print the price in euros, prepending the Unicode string for the euro sign (`\u20AC`) to the numeric price. Make the print statement work so that there is no space between the euro sign and the price.

In [23]:
exchange_rate = 0.9176
price_in_euros = price * exchange_rate
print(f"The item {item_name} has a price of \u20AC{price_in_euros:.2f}")


The item smoke shifter has a price of €412.92


4. Convert the catalog dictionary in problem 2 to a pandas Series. Using `.loc`, print the name of the item with catalog number `19x5`. Then, using `.iloc`, print the name of the second item in the list.

In [24]:
import pandas as pd
catalog_series = pd.Series(catalog)

# Using .loc to print the name of the item with catalog number '19x5'
print(catalog_series.loc['19x5'])

# Using .iloc to print the name of the second item in the list
print(catalog_series.iloc[1])

smoke shifter
flange


5. Convert the two dictionaries in problem 2 to a pandas DataFrame using `pd.DataFrame`. Display the DataFrame below the cell in tabular form.

In [25]:
import pandas as pd

catalog_df = pd.DataFrame(list(catalog.items()), columns=['Catalog Number', 'Item Name'])
price_df = pd.DataFrame(list(price_dict.items()), columns=['Catalog Number', 'Price'])

catalog_df
price_df

Catalog Number   Price
0           1008    3.25
1           2149    5.00
2           19x5  450.00
3            992  600.00

6. Using the DataFrame you just created, print the Series for the price column. Then print the Series for the catalog number 2149 row.

In [43]:
price_series = price_df['Price']
print(price_series)
print("The price of the second item on the list is ${:.2f}".format(price_series[1]))

0      3.25
1      5.00
2    450.00
3    600.00
Name: Price, dtype: float64
The price of the second item on the list is $5.00


7. The second line of code below reads in a CSV containing climate data: the average precipitation and temperature for months the year 1879 in Mesa, Arizona. Display the first 6 rows of the DataFrame below the cell in tabular form. 

In the following code cell, print the following:
- the data for March 1879 (as a Series).
- the average temperture for July 1879.


In [57]:
import pandas as pd
climate = pd.read_csv('https://github.com/HeardLibrary/digital-scholarship/raw/master/data/codegraf/mesa_climate.csv')

# Set the row index to be the 'month' column
climate = climate.set_index('month')

# Display the first 6 rows of the DataFrame
print(climate.head(6))

print(" ")
print("March's data for 1879 is below:")

march_data = climate.loc['Mar']
print(march_data)

print(" ")

july_avg_temp = climate.loc['Jul', 'tavg']
print("The average temperature for July is:", july_avg_temp)


        ppt  tavg
month            
Jan    92.8  12.1
Feb    19.1  10.1
Mar    18.2  11.8
Apr     0.0  19.2
May     4.1  25.0
Jun     0.0  28.1
 
March's data for 1879 is below:
ppt     18.2
tavg    11.8
Name: Mar, dtype: float64
 
The average temperature for July is: 32.4


8. Create a list that contains the names of the days of the week. Using a `for` loop, print the days of the week.

In [67]:
days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

for day in days_of_week:
    print(day)


Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday


9. Using a `for` loop and the `.iterrows` method, print the month abbreviation and average temperature in Mesa for each month in 1879 together on the same line. (Remember that the month abbreviation is now the index for the row.) To make the output clearer, print a header explaining what the columns are before you print the values.

In [59]:
print("Month Abbreviation\tAverage Temperature")
for index, row in climate.iterrows():
    print(f"{index}\t\t\t{row['tavg']}")


Month Abbreviation	Average Temperature
Jan			12.1
Feb			10.1
Mar			11.8
Apr			19.2
May			25.0
Jun			28.1
Jul			32.4
Aug			32.2
Sep			28.2
Oct			19.5
Nov			14.5
Dec			8.7


10. Create a variable called `sum` and set its value to zero. Create a `for` loop that steps through each month and adds the precipitation value for each month to the `sum` variable. Recall that

```
sum += number
```

is a shortcut for

```
sum = sum + number
```

After you add up all of the values, print the value of the average precipitation for all months of the year. (Don't worry about weighting the monthly values by the length of the month.)

In [62]:
total_precipitation = 0

for index, row in climate.iterrows():
    total_precipitation += row['ppt']

average_precipitation = total_precipitation / len(climate)
print("The average precipitation for all months of the year is:", round(average_precipitation, 2))


The average precipitation for all months of the year is: 19.04


11. Because pandas is designed for vectorized operations, there is an easier way to find the average precipitation for all of the months. Simply append the `.mean()` method to the precipitation column of the DataFrame. (The mean method does not require any arguments.) Print the result. Is it the same as what you got using the `for` loop?

In [64]:
average_precipitation_pandas = climate['ppt'].mean()
print("The average precipitation for all months of the year is:", round(average_precipitation_pandas, 2))


The average precipitation for all months of the year is: 19.04
